"""Curated Phu Quoc hotels and Agoda property IDs."""

# Agoda city ids for Phu Quoc Island
AGODA_CITY_ID = 17194

HOTELS = [
    # popular luxury / 5-star
    {"id": 1624474, "name": "JW Marriott Phu Quoc Emerald Bay", "popularity": "popular", "district": "Bai Khem", "booking_slug": "jw-marriott-phu-quoc-emerald-bay-resort-spa"},
    {"id": 3648660, "name": "InterContinental Phu Quoc Long Beach", "popularity": "popular", "district": "Long Beach", "booking_slug": "intercontinental-hotels-phu-quoc-long-beach-resort"},
    {"id": 34249576, "name": "New World Phu Quoc Resort", "popularity": "popular", "district": "Bai Khem", "booking_slug": "new-world-phu-quoc-resort-kien-giang"},
    {"id": 21774297, "name": "Regent Phu Quoc", "popularity": "popular", "district": "Bai Dai / Starbay", "booking_slug": "regent-phu-quoc"},
    {"id": 4518431, "name": "Premier Village Phu Quoc", "popularity": "popular", "district": "Bai Khem", "booking_slug": "premier-village-phu-quoc-resort"},
    {"id": 1624152, "name": "Fusion Resort Phu Quoc", "popularity": "popular", "district": "Vung Bau"},
    {"id": 569108, "name": "Salinda Resort Phu Quoc", "popularity": "popular", "district": "Long Beach", "booking_slug": "salinda-premium-resort-and-spa"},
    {"id": 625168, "name": "Vinpearl Resort & Spa Phu Quoc", "popularity": "popular", "district": "Bai Dai", "booking_slug": "vinpearl-resort-phu-quoc"},
    {"id": 1985199, "name": "Meliá Vinpearl Phu Quoc", "popularity": "popular", "district": "Bai Dai", "booking_slug": "melia-vinpearl-phu-quoc"},
    {"id": 9776735, "name": "Pullman Phu Quoc Beach Resort", "popularity": "popular", "district": "Long Beach", "booking_slug": "pullman-phu-quoc"},
    {"id": 5442703, "name": "Radisson Blu Resort Phu Quoc", "popularity": "popular", "district": "Bai Dai", "booking_slug": "radisson-blu-resort-phu-quoc"},
    {"id": 2163073, "name": "Wyndham Grand Phu Quoc", "popularity": "popular", "district": "Bai Dai", "booking_slug": "wyndham-grand-phuquoc"},
    {"id": 14654959, "name": "Mövenpick Resort Waverly Phu Quoc", "popularity": "popular", "district": "Ong Lang", "booking_slug": "movenpick-resort-waverly-phu-quoc"},
    {"id": 14676909, "name": "Mövenpick Villas & Residences Phu Quoc", "popularity": "mid", "district": "Ong Lang", "booking_slug": "movenpick-residences-phu-quoc"},
    {"id": 1157572, "name": "Novotel Phu Quoc Resort", "popularity": "popular", "district": "Long Beach", "booking_slug": "novotel-phu-quoc-resort"},
    {"id": 70425, "name": "La Veranda Resort Phu Quoc MGallery", "popularity": "popular", "district": "Long Beach", "booking_slug": "test-grand-mercure-la-veranda-phu-quoc-do-not-book"},
    {"id": 1032420, "name": "Sheraton Phu Quoc Long Beach Resort", "popularity": "popular", "district": "Bai Dai", "booking_slug": "sheraton-phu-quoc-long-beach-resort"},
    {"id": 5972590, "name": "Premier Residences Emerald Bay", "popularity": "popular", "district": "Bai Khem", "booking_slug": "premier-residences-phu-quoc-emerald-bay"},
    {"id": 1266957, "name": "SOL by Meliá Phu Quoc", "popularity": "mid", "district": "Long Beach", "booking_slug": "sol-phu-quoc"},
    {"id": 31187083, "name": "Sailing Club Signature Resort", "popularity": "mid", "district": "Long Beach", "booking_slug": "sailing-club-signature-resort-phu-quoc"},
    {"id": 4968811, "name": "Dusit Princess Moonrise", "popularity": "mid", "district": "Long Beach", "booking_slug": "dusit-princess-moonrise-beach-resort"},
    {"id": 21774298, "name": "Crowne Plaza Phu Quoc Starbay", "popularity": "mid", "district": "Bai Dai / Starbay"},
    {"id": 2061878, "name": "Nam Nghi Coral Peninsula", "popularity": "mid", "district": "Vung Bau"},
    {"id": 5943665, "name": "Sunset Sanato Resort & Villas", "popularity": "mid", "district": "Long Beach", "booking_slug": "sunset-sanato-resort-amp-spa"},
    # lesser-known / boutique / value
    {"id": 7008284, "name": "Best Western Premier Sonasea", "popularity": "lesser-known", "district": "Long Beach", "booking_slug": "best-western-premier-sonasea-phu-quoc"},
    {"id": 83294991, "name": "WorldHotels Long Beach Resort", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 2430159, "name": "Seashells Phu Quoc Hotel & Spa", "popularity": "mid", "district": "Long Beach", "booking_slug": "the-seashell"},
    {"id": 96572, "name": "Cassia Cottage Resort & Spa", "popularity": "mid", "district": "Long Beach", "booking_slug": "cassia-cottage"},
    {"id": 48370, "name": "Mango Bay Resort", "popularity": "mid", "district": "Ong Lang"},
    {"id": 148661, "name": "Chen Sea / The Slate", "popularity": "mid", "district": "Ong Lang", "booking_slug": "chen-sea-resort-spa"},
    {"id": 400217, "name": "Famiana Resort & Spa", "popularity": "mid", "district": "Long Beach"},
    {"id": 8836100, "name": "L'Azure Resort and Spa", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 21967772, "name": "Ocean Bay Phu Quoc Resort & Spa", "popularity": "lesser-known", "district": "Ong Lang"},
    {"id": 47021962, "name": "Grand Resort Ocean Bay", "popularity": "lesser-known", "district": "Ong Lang"},
    {"id": 35958304, "name": "Wyndham Garden Grandworld", "popularity": "lesser-known", "district": "Bai Dai"},
    {"id": 14695651, "name": "Peppercorn Beach Resort", "popularity": "lesser-known", "district": "Bai Dai"},
    {"id": 11081947, "name": "Paralia Khem Beach", "popularity": "lesser-known", "district": "Bai Khem"},
    {"id": 1624612, "name": "Muong Thanh Luxury Phu Quoc", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 6352970, "name": "An Phu Hotel", "popularity": "lesser-known", "district": "Duong Dong"},
    {"id": 60710642, "name": "Rocks Beach Boutique", "popularity": "lesser-known", "district": "Ham Ninh"},
    {"id": 2061904, "name": "Brenta Phu Quoc Hotel", "popularity": "lesser-known", "district": "Duong Dong"},
    {"id": 406794, "name": "Bamboo Cottages", "popularity": "lesser-known", "district": "Vung Bau"},
    {"id": 1119483, "name": "Praha Hotel", "popularity": "lesser-known", "district": "Duong Dong"},
    {"id": 983880, "name": "Bauhinia Resort Phu Quoc", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 39897314, "name": "Green Inn Phu Quoc Hotel", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 4999788, "name": "Coral Bay Hotel & Resort", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 3007308, "name": "An Nhien Retreat", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 32482497, "name": "Ann Hotel & Spa Khem Beach", "popularity": "lesser-known", "district": "Bai Khem"},
    {"id": 9612717, "name": "Sunset Beach Resort & Spa", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 2570684, "name": "The Palmy Phu Quoc Resort", "popularity": "lesser-known", "district": "Long Beach"},
    {"id": 65344078, "name": "Novus Sol Hotel Sunset Town", "popularity": "lesser-known", "district": "An Thoi"},
    {"id": 181816, "name": "Hawaii Resort Phu Quoc", "popularity": "lesser-known", "district": "Long Beach"},
]
